### ISSUE TITLE
Which ESM model to use for UCE input?

### ISSUE THREAD

**Issue by vinettey** [snap-stanford/UCE#13]
Hi, I’m trying to run the saturn code to generate protein embeddings that I’ll use for input into UCE. I noticed that the saturn code uses a smaller model (esm1b_t33_650M_UR50S). I just wanted to confirm that you’re generating UCE protein embeddings using the biggest ESM2 model (https://huggingface.co/facebook/esm2_t48_15B_UR50D). I just replaced the line in the saturn code that specified the model with the 15B parameter ESM2 version. Is that correct Thank you for the extra information!

**Comment by Yanay1** [comment]
Yes that is correct! UCE uses the 15B ESM2 model.

There are quite a few pre-calculated ESM2 embeddings here: https://drive.google.com/drive/folders/1_Dz7HS5N3GoOAG6MdhsXWY1nwLoN13DJ which might contain the species you are interested in.

**Comment by vinettey** [comment]
Hi! I encountered a mismatch error when running UCE on ESM embedding of a new species. 
`RuntimeError: Error(s) in loading state_dict for TransformerModel:
        size mismatch for pe_embedding.weight: copying a param with shape torch.Size([145469, 5120]) from checkpoint, the shape in current model is torch.Size([19910, 5120]).`

I generated protein embeddings with the ESM2 model by the following codes:
`python extract.py esm2_t48_15B_UR50D $DATA_PATH/$NAME.clean.fa $DATA_PATH/$NAME.clean.fa_esm2 --include mean  --truncate
python sequence_model/map_gene_symbol_to_protein_ids.py \
    --fasta_path $DATA_PATH/$NAME.pep.all.fa \
    --save_path $DATA_PATH/$NAME.gene_symbol_to_protein_ID.json
python sequence_model/convert_protein_embeddings_to_gene_embeddings.py \
    --embedding_dir $DATA_PATH/$NAME.clean.fa_esm2/ \
    --gene_symbol_to_protein_ids_path $DATA_PATH/$NAME.gene_symbol_to_protein_ID.json \
    --embedding_model ESM2 \
    --save_path /net/shendure/vol1/home/weiy666/UCE/model_files/protein_embeddings/$NAME.gene_symbol_to_embedding_ESM2.pt
`
Could you please help checking what might went wrong here? Thanks!

**Comment by Evenlyeven** [comment]
> Yes that is correct! UCE uses the 15B ESM2 model.
> 
> There are quite a few pre-calculated ESM2 embeddings here: https://drive.google.com/drive/folders/1_Dz7HS5N3GoOAG6MdhsXWY1nwLoN13DJ which might contain the species you are interested in.


Thank you for providing this great tool and for the detailed information shared in this issue. I have a follow-up question regarding the ESM2 models.

Do I need to use the largest ESM2 model (esm2_t48_15B_UR50D) for `convert_protein_embeddings_to_gene_embeddings.py`? I am asking because during a test run with the smaller model (esm2_t33_650M_UR50D), I encountered `KeyError: 48`.

Is there something specific to the smaller model that might be causing this issue?

Thanks in advance for your help!

**Comment by Evenlyeven** [comment]
> Yes that is correct! UCE uses the 15B ESM2 model.
> 
> There are quite a few pre-calculated ESM2 embeddings here: https://drive.google.com/drive/folders/1_Dz7HS5N3GoOAG6MdhsXWY1nwLoN13DJ which might contain the species you are interested in.

Thank you for providing this great tool and for the detailed information shared in this issue. I have a follow-up question regarding the ESM2 models:

Do I need to use the largest ESM2 model (esm2_t48_15B_UR50D) for `convert_protein_embeddings_to_gene_embeddings.py`? I am asking because during a test run with the smaller model (esm2_t33_650M_UR50D), I encountered a KeyError: 48 in the script.

Is there something specific to the smaller model that might be causing this issue?

Thanks in advance for your help!
