### ISSUE TITLE
Preprocessing of chicken retina dataset

### ISSUE THREAD

**Issue by JiriBruthans** [snap-stanford/UCE#35]
Hi. Could you please share the code for preprocessing the dataset GSE159107 before it was used as input into UCE to generate chicken_retina.h5ad?

**Comment by Yanay1** [comment]
You can download the the author cell types from the SCP rather than GSE: https://singlecell.broadinstitute.org/single_cell/study/SCP1159/a-cell-atlas-of-the-chick-retina-based-on-single-cell-transcriptomics#study-summary

Note: you need to create an account to download files

Then subset the expression matrices to match the barcodes in the cell type marker file (these are called clusterfiles). 

Finally, cell types were coarsened to just the cell type name rather than the cluster.
